# Generated by Django 3.0.11 on 2020-11-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_comprobante',
            field=models.CharField(choices=[('Boleta', 'Boleta'), ('Factura', 'Factura')], default='Boleta', max_length=7),
        ),
    ]
