# Generated by Django 3.0.11 on 2020-11-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201116_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='RUC',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_comprobante',
            field=models.CharField(choices=[('Boleta', 'Boleta'), ('Factura', 'Factura')], default='Boleta', max_length=7),
        ),
    ]
