# Generated by Django 3.0.11 on 2020-11-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201121_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tarifa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
