# Generated by Django 3.0.11 on 2020-11-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201121_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='preferencias',
        ),
        migrations.AddField(
            model_name='cliente',
            name='preferencias',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Categoria'),
        ),
    ]
