# Generated by Django 3.0.11 on 2020-11-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201124_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='preferencias',
        ),
        migrations.AddField(
            model_name='cliente',
            name='preferencias',
            field=models.ManyToManyField(to='main.Categoria'),
        ),
    ]
